@startuml
class CadSystemView <<partial>> {
    + CadSystemView(cadSystemViewModel:CadCostEditViewModel, serviceProvider:IServiceProvider)
}
Window <|-- CadSystemView
CadSystemView --> "_cadSystemViewModel" CadCostEditViewModel
@enduml
