@startuml
!include .\\TRPO.Data\CadSystemsContext.puml
!include .\\TRPO.Data\GenericRepository.puml
!include .\\TRPO.Data\IEntity.puml
!include .\\TRPO.Data\IGenericRepository.puml
!include .\\TRPO.WPF\App.xaml.puml
!include .\\TRPO.Data\Models\CadCost.puml
!include .\\TRPO.Data\Models\CadSystem.puml
!include .\\TRPO.Data\Models\CadSystemType.puml
!include .\\TRPO.Data\Models\OperatingSystem.puml
!include .\\TRPO.Data\Models\TechnicalRequirement.puml
!include .\\TRPO.WPF\ViewModels\CadCostEditViewModel.puml
!include .\\TRPO.WPF\ViewModels\CadSystemsEditViewModel.puml
!include .\\TRPO.WPF\ViewModels\CadSystemsListViewModel.puml
!include .\\TRPO.WPF\Views\AssemblyInfo.puml
!include .\\TRPO.WPF\Views\CadSystemsEditView.xaml.puml
!include .\\TRPO.WPF\Views\CadSystemsListView.xaml.puml
!include .\\TRPO.WPF\Views\CadSystemView.xaml.puml
!include .\\TRPO.Data\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\TRPO.Data\obj\Debug\net6.0\TRPO.Data.AssemblyInfo.puml
!include .\\TRPO.Data\obj\Debug\net6.0\TRPO.Data.GlobalUsings.g.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\App.g.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\App.g.i.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\CadSystemsEditView.g.i.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\CadSystemView.g.i.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\GeneratedInternalTypeHelper.g.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\GeneratedInternalTypeHelper.g.i.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\MainWindow.g.i.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_0lutdi2x_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_0sgjbrgl_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_1njazy03_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_1u5mm15e_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_1ulnff53_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_2d4w2pim_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_2gglrkhg_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_2uun2yia_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_3ic3ebrk_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_3k0jxsn1_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_4cdj5vks_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_4g4x2d0p_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_5vnop4wq_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_aivivl12_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_ci3ykmjy_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_cyoibsw5_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_d1mumu0c_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_d4b2kdaq_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_dmlcs14n_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_dyymke0y_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_eg3nondt_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_epy5g2at_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_fcrjnh1h_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_fdgmdxre_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_fmoklfj4_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_fpxx1nez_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_g05y3dd5_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_ggregctx_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_giuimaw2_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_gxxdoay1_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_hafrfl4o_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_hpjdt3xy_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_hyrqgeg3_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_ir0gnqey_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_itf2tnno_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_iu2bnmrs_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_jhhki1jj_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_k33bnvyq_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_keq5oqj1_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_kkqqmkkr_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_kx2yla0k_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_lv1q1txb_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_njn3jn2z_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_p4rpjelt_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_p5y3efjy_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_piyot5bp_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_pmf4p4dn_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_qwd1elg2_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_ructtu45_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_sd0rsaij_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_shwwzksn_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_spckhjzc_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_t0hgxqyu_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_um2xwiti_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_uyzek2lk_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_vxqmps25_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_wob2ewxg_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_xdeq003o_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_z1ofwbvv_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_zdkdh242_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_ze35dlkf_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\TRPO.WPF_zrp241ie_wpftmp.AssemblyInfo.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\Window1.g.i.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\Views\App.g.i.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\Views\CadSystemsEditView.g.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\Views\CadSystemsEditView.g.i.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\Views\CadSystemsListView.g.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\Views\CadSystemsListView.g.i.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\Views\CadSystemView.g.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\Views\CadSystemView.g.i.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\Views\MainWindow.g.i.puml
!include .\\TRPO.WPF\obj\Debug\net6.0-windows\Views\OperatingSystemsView.g.i.puml
@enduml
